airbnb/goji-js

- lerna.json
- packages/cli/package.json
- packages/core/package.json
- packages/testing-library/package.json
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/plugins/shim/meta.ts
- packages/webpack-plugin/src/plugins/shim/patches/array.ts
- packages/webpack-plugin/src/plugins/shim/patches/arrayBuffer.ts
- packages/webpack-plugin/src/plugins/shim/patches/index.ts
- packages/webpack-plugin/src/plugins/shim/patches/number.ts
> This PR copies code from internal repo to pubic repo.
1. Upgrade version to 0.7.6
2. Patch `Array`, `Number`, `ArrayBuffer` in the GojiShimPlugin
> Update goji to 0.7.6

- packages/cli/src/index.ts
Since we began using `@goji/cli` the right way to pass `target` and `nodeEnv` to Webpack is 
`yarn <start or build> [target]`.
If you run `yarn start`, the `nodeEnv` should be `development`.
If you run `yarn build alipay, the `nodeEnv` should be `development` and `target` should be `alipay`.
> Fix target for webpack config

- packages/cli/src/config/webpack.config.ts
- packages/cli/src/index.ts
- packages/core/src/components/factoryComponents.ts
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/plugins/bridge.ts
- packages/webpack-plugin/src/plugins/collectUsedComponents.ts
- packages/webpack-plugin/src/shared/index.ts
- packages/webpack-plugin/src/types/index.ts
The bridge files look like this,
```html
<block wx:elif="{{type === 'button'}}">
<button
data-goji-id="{{id || -1}}"
class="{{props.className}}"
style="{{props.style || ''}}"
...
>xxx</button>
</block>
<block wx:elif="{{type === 'camera'}}">
<camera>...</camera>
</block>
```
Normally, GojiJS generates all components in bridge files. It may cause bridge files too large that exceeds the 2MB main package limitation. For reducing the bundle size, GojiJS use an unstable config file `unstable_componentWhitelist` to filter the needed components.
```js
// goji.config.js
module.exports = {
unstable_componentWhitelist: ['view', 'button']
}
```
Of course, it's un-scalable and hard to maintain in a large project such as Airbnb.
This PR removed the `unstable_componentWhitelist`. And use static …
> Collect used components while compling

- packages/core/src/reconciler/__tests__/instance.test.tsx
- packages/core/src/reconciler/instance.ts
- packages/webpack-plugin/src/constants/__tests__/components.test.ts
- packages/webpack-plugin/src/constants/components.ts
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/plugins/bridge.ts
- packages/webpack-plugin/src/utils/__tests__/components.test.ts
- packages/webpack-plugin/src/utils/components.ts
- packages/webpack-plugin/templates/components.wxml.ejs
- packages/webpack-plugin/templates/components/scroll-view.json.ejs
- packages/webpack-plugin/templates/components/swiper.json.ejs
- packages/webpack-plugin/templates/item.json.ejs
- packages/webpack-plugin/templates/leaf-components.wxml.ejs
- packages/webpack-plugin/templates/subtree.json.ejs
This PR
1. Enable wrapped components support for all platforms.
We use `target` to check which components should be wrapped like `isWrapped: ['wechat', 'qq'].includes(target)` . So we can add wrapped component for any platform.
2. Fix the wrong `subtreeId` in non-wehcat-like platforms, like Alipay.
I use `process.env.GOJI_WRAPPED_COMPONENTS` replace the hard code list. The legacy list should be applied for Alipay, Baidu and etc.
The wrong `subtreeId` causes `getComponentInstance` pending forever.
> Refactor wrapped components to support all platforms

- packages/core/src/reconciler/__tests__/instance.test.tsx
- packages/core/src/reconciler/instance.ts
For non-WeChat platforms, because they don't need subtree to pass by the recursive template issue the `subtree id` should always be `undefined`. In the previous codes, we forget to check the build target for them.
Wrong subtree id causes the `ref.getComponentsInstance` promise remains pending forever. Some features may fail, like `wx.createIntersectionObserver`.
> Fix wrong non-WeChat platforms subtree id

- packages/cli/src/config/babel.config.ts
- packages/cli/src/config/webpack.config.ts
- packages/core/package.json
- packages/demo-todomvc/package.json
- packages/testing-library/package.json
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/loaders/configFile.ts
Since `@goji/cli` provides the whole build tools for a GojiJS project, it should always resolve dependencies from its `node_modules`.
To explain it let's consider such a situation that the GojiJS project `Foo` was generated by GojiJS CLI, and now we add a new dependency like `file-loader` to it.
```
└── foo
└── node_modules
├── @goji
│   └── cli
│       └── node_modules
│           └── file-loader v1
└── file-loader v2
```
In this case, `@goji/cli` should always `file-loader v1` rather than `v2` because mismatch dependencies may not work well.
But in Babel and WebPack, the string value like `file-loader` means they would resolve the module from `process.env.PWD`. This result in the wrong module resolved.
I use `require.resolve` to return the full path of Babel preset/plugins and WebPack …
> Always use bundled dependencies

- packages/core/src/reconciler/instance.ts
The `getComponentInstance` API doesn't on QQ, because we forgot to enable subtree id.
The `subtree id` is the uniq id for the `<Subtree>` component. We use this id to detect the `this` context of component which the ref element was rendered inside.
> [core] Fix QQ getComponentInstance support

- packages/webpack-plugin/src/plugins/shim/patches/__tests__/array.test.ts
- packages/webpack-plugin/src/plugins/shim/patches/array.ts
`new Array()` and `new Array(a, b, c)` doesn't work in GojiJS because of an internal issue in `WebpackShimPlugin`.
The `WebpackShimPlugin` patches several global variables to fix the prototype frozen issue on WeChat. These variables includs `Array` / `String` / `Promise and etc.
But the implement of `PatchedArray` has a certain issue. It only support the `new Array(length)` usage and others may fails.
| source            | expect          | in fact         | result |
| ----------------- | --------------- | --------------- | ------ |
| new Array()       | []              | [undefined]     | ✘      |
| new Array(3)      | [undefined * 3] | [undefined * 3] | ✔      |
| new Array(3, 'a') | [3, 'a']        | [undefined * 3] | ✘      |
Of course, this bug might affect 3rd libraries and business …
> Fix wrong result of `new Array` due to webpack shim plugin

- packages/core/src/components/factoryComponents.ts
- packages/core/src/events.ts
- packages/webpack-plugin/src/constants/components.ts
There are two event types, `long tap` and `long press`, to watch the long press interactive action. But they have inconsistent behaviors on different platforms.
This PR tries to deprecate `long tap` event and forces using `long press` instead.
1. `long tap` is useless and deprecated. For example, WeChat official document says *手指触摸后，超过350ms再离开（推荐使用longpress事件代替）*
2. Inconsistent behaviors make developers confused.
| Platform              | WeChat                | QQ                    | Baidu              | Alipay           | Toutiao               |
| --------------------- | --------------------- | --------------------- | ------------------ | ---------------- | --------------------- |
| longpress support     | ✓                     | ✓                     | ✓                  | ✘ …
> Deprecate onLongTap and always use onLongPress

- packages/webpack-plugin/src/constants/components.ts
- packages/webpack-plugin/src/utils/components.ts
This is an internal refactor of GojiJS Webpack Plugins. No API was changed.
1. Rename `prop.value` to `prop.defaultValue`.
2. Remove useless `prop.type`.
> Refactor components meta data in webpack plugins part 1

- packages/cli/package.json
- packages/cli/src/config/fasterBabelLoaderForMacro.ts
- packages/cli/src/config/webpack.config.ts
To support `@goji/macro` feature, the Webpack always create a new instance of `babel` in each call of `babel-loader`.
But in fact, we could only parse files that include `import from macro` statement. So I create a `faster-babel-loader-for-macro` that check whether the file match [`/[./]macro(\.c?js)?$/`](https://github.com/kentcdodds/babel-plugin-macros/blob/18d79d3ac3c2975565e7897d2233cf498f15ffb5/src/index.js#L5) regex before parse them.
```tsx
import { registerPluginComponent } from '@goji/macro'; // should parse this file
```
This PR reduced 25% Webpack bundling time.
|     | Before | After |
| --- | ------ | ----- |
| 1   | 13.3   | 10.26 |
| 2   | 12.65  | 9.63  |
| 3   | 12.82  | 9.5   |
| 4   | 12.76  | 9.21  |
| 5   | 12.67  | 9.52  |
| Avg | 12.84  | 9.624 |
> Extract faster-babel-loader-for-macro to speed up build time

- packages/cli/src/config/webpack.config.ts
In different `nodeEnv` and `target`, the Linaria should use different `cacheDirectory`.
This is an example.
```css
/* nodeEnv === 'development' */
.logo_l7007{margin-top:180rpx;color:#ff385c;}
```
```css
/* nodeEnv === 'production' */
.l7007{margin-top:180rpx;color:#ff385c;}
```
> Fix Linaria `cacheDirectory`

- packages/webpack-plugin/src/loaders/configFile.ts
- packages/webpack-plugin/src/plugins/entry.ts
1. Create a new folder `test` anywhere outside the `goji-js` repo.
2. Link the `goji-js/packages/demo-todomvc` into `test` folder.
3. Run yarn build in `test/demo-todomvc`.
4. Useless files are generated in the `src` folder.
Webpack always resolve the symlink in the `this.request` of a loader.
For example, we use `/path/to/configFile?target=wechat!./pages/index` to process the `pages/index.config.ts` file. Webpack always convert the request to `/path/to/configFile?target=wechat!/path/to/test/src/pages/index` rather than keeping the original request. So it is hard to calculate the correct entry path, which is the relative path from request to root context.
In this PR, I add a new loader's param to passthrough the entry path from the plugin to loader.
> Fix symlink support in configFile loader

- packages/cli/src/config/babel.config.ts
> You can try in this demo: `packages/demo-todomvc`
1. Enable WeChat live plugin by adding these lines into `app.json`.
```json
"plugins": {
"live-player-plugin": {
"version": "1.2.0",
"provider": "wx2b03c6e691cd7370"
}
}
```
2. Change the test app id to a real one which has the permission of using [WeChat Live Plugin](https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/live-player-plugin.html).
2. Run `yarn build`.
3. Preview the `dist/wechat` folder by WeChat Dev Tool in a iOS 11 device.
By default GojiJS use `import 'core-js/stable';` as polyfill. It contains a list of ES features.
One of them is `core-js/modules/es.json.stringify.js`. This feature fails to run on legacy iOS devices, like iOS 11/12, with raising a `TypeError` and then cause a white screen issue.
This …
> Change babel.config.js to fix iOS white screen issue

- packages/core/src/components/componentsTypes.ts
- packages/webpack-plugin/templates/components.wxml.ejs
- packages/webpack-plugin/templates/components/input.js.ejs
- packages/webpack-plugin/templates/components/input.wxml.ejs
- packages/webpack-plugin/templates/components/scroll-view.js.ejs
- packages/webpack-plugin/templates/components/scroll-view.wxml.ejs
- packages/webpack-plugin/templates/components/swiper-item.wxml.ejs
- packages/webpack-plugin/templates/components/swiper.js.ejs
- packages/webpack-plugin/templates/components/swiper.wxml.ejs
- packages/webpack-plugin/templates/components/textarea.js.ejs
- packages/webpack-plugin/templates/components/textarea.wxml.ejs
- packages/webpack-plugin/templates/leaf-components.wxml.ejs
The PR add the `id` attribute for all elements.
There are some use cases of `id`:
1. [wx.pageScrollTo](https://developers.weixin.qq.com/miniprogram/dev/api/ui/scroll/wx.pageScrollTo.html) support id selector.
2. [wx.createMapContext](https://developers.weixin.qq.com/miniprogram/dev/api/media/map/wx.createMapContext.html) need map has a `id`.
3. CSS can use `id` selector.
This PR increase 1.4kb bundle size in our Mini Program, which should be acceptable.
> Enable `id` for all elements

- packages/cli/src/config/webpack.config.ts
Linaria use `node_modules/.cache/` to store temporary .css files that cause Webpack re-compile twice for a single change.
So this PR add an `ignored: [/node_modules\/\.cache/]` option to step watch cache folders.
> Stop watching `node_modules/.cache` folder in dev mode

- packages/cli/src/config/webpack.config.ts
- packages/cli/tsconfig.json
This PR enables cache for `babel-loader` to speed up Webpack bundle.
In our miniapp, it reduces 40% time cost (from 77s to 45s ) for running `yarn build`.
Docs: https://github.com/babel/babel-loader#options
> Enable cache for `babel-loader` to speed up Webpack bundle

- packages/cli/src/config/webpack.config.ts
Revert https://github.com/airbnb/goji-js/pull/73 beacuse Linaria fails to refresh in dev mode.
> Revert "stop watching `node_modules/.cache` folder in dev mode"

- packages/core/src/adaptor/__tests__/__snapshots__/wechat.test.tsx.snap
- packages/core/src/adaptor/common.ts
- packages/core/src/adaptor/wechat.tsx
- packages/core/src/constants.ts
- packages/core/src/container.tsx
- packages/core/src/reconciler/hostConfig.ts
- packages/core/src/reconciler/instance.ts
This PR refactor internal data structure of `@goji/core`. No exported API is changed.
Before:
`Container` is a superset of `ElementInstance`. Both of them has similar methods like `appendChild`/`insertBefore`.
Many codes are duplicated between these two classes.
After:
Introduce a new virtual root element called  `GOJI_VIRTUAL_ROOT`. 
```tsx
class Container {
public virtualRootElement = new ElementInstance(GOJI_VIRTUAL_ROOT, {}, [], this);
}
```
It contains both root dom and portal doms and looks like this:
```html
<GOJI_VIRTUAL_ROOT>
<view>the root dom</view>
<view>the portal dom 1</view>
<view>the portal dom 2</view>
<view>the portal dom 3</view>
...
</GOJI_VIRTUAL_ROOT>
```
But, we will never render such a `GOJI_VIRTUAL_ROOT` element into pages. We only render its children elements. So …
> Refactor container code by introducing a new virtual root element

- packages/cli/src/config/postcss.config.ts
- packages/cli/src/config/webpack.config.ts
- packages/cli/src/index.ts
- packages/webpack-plugin/src/plugins/based.ts
- packages/webpack-plugin/src/plugins/bridge.ts
- packages/webpack-plugin/src/types/index.ts
`unsafe_integrationMode` is an internal option used inside Airbnb company and is no longer needed.
> Remove integration mode

- .github/workflows/ci.yml
- https://nodejs.medium.com/node-js-16-available-now-7f5099a97e70
- node 10 LTS ends end of April
> use node 16, deprecate node 10

- packages/cli/package.json
- packages/core/src/partial/index.tsx
- packages/core/src/utils/effects.ts
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/plugins/shim/patches/promise.ts
- yarn.lock
This PR upgrade dependencies by running `yarn upgrade-interactive`. It should only upgrade `patch` versions.
> Upgrade deps by `yarn upgrade-interactive`

- packages/webpack-plugin/src/constants/components.ts
- packages/webpack-plugin/src/templates/components/__tests__/__snapshots__/wrapped.js.test.tsx.snap
These bad cases can reproduce the issue that empty `setting` field cause the map fails to render on iOS devices.
GojiJS ( v0.11.0 ):
```tsx
import React from 'react';
import { render, Map } from '@goji/core';
render(<Map latitude={31.2253} longitude={121.45928} />);
```
Native WeChat Mini Program:
https://developers.weixin.qq.com/s/0e9NPsmd7fss
I thought several solutions, but non of them are 100% perfect to solve the issue.
1. Set default value for `setting`, including these ways:
* Add `value: {}` for `properties` field in `map.js`
* Add `setting="{{setting || defauleValue}}"` in `map.wxml`, but literal `{}` doesn't work in wxml.
2. Don't render `setting="{{setting}}"` field in `map.wxml` at all.
By now, I prefer to disable the usage of `setting` property to unblock white screen issue. …
> Disable <map>'s setting usage temporary

- packages/create-goji-app/package.json
- packages/create-goji-app/src/generator.ts
- yarn.lock
Because `globby@12` only support ES Module but `create-goji-app` cannot uses it now.
> Revert globby version

- packages/create-goji-app/src/__tests__/index.test.ts
- packages/create-goji-app/src/generator.ts
- packages/create-goji-app/templates/package.json
- packages/create-goji-app/tsconfig.json
The `create-goji-app` CLI seems not work.
I fixed it and adds some test cases.
The `packages/create-goji-app/src/__tests__/index.test.ts` will create a GojiJS app in `/tmp/.create-goji-app/my-goji-app` and run `yarn build` for it.
> Fix create-goji-app cli and add test cases

- packages/goji.js.org/docs/testing.md
- packages/goji.js.org/website/translated_docs/zh-CN/testing.md
- packages/testing-library/src/__tests__/rendered.test.tsx
- packages/testing-library/src/index.ts
- packages/testing-library/src/rendered.ts
If you'd like to restrict your query in specific container, you can use `within`.
```tsx
const Comp = () => (
<View testID="view">
<Button>Click me</Button>
</View>
);
const wrapper = render(<Comp />);
const view = wrapper.getByTestId('view');
const buttonInsideView = within(view).getByText('Click me');
```
Inspired from:
https://github.com/testing-library/dom-testing-library/blob/d347302d6b17280b71505d55d0cb9cda376b95cc/src/get-queries-for-element.js#L13
https://github.com/callstack/react-native-testing-library/blob/e1d80d65fca628c014f8bd555670d9871f3ac6ee/src/within.js#L7
> Add `within` method for testing library

- packages/core/src/components/componentsTypes.ts
- packages/webpack-plugin/src/constants/components.ts
According to [this document](https://developers.weixin.qq.com/miniprogram/dev/component/map.html) the default value of `enable-poi` should be `true` not `false`.
> Fix an issue that <map> enable-poi should default to true

- packages/cli/src/config/webpack.config.ts
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/src/plugins/chunks.ts
Before:
use placeholder in `webpack.config.js`
=> load `SplitChunksPlugin` and `RuntimeChunkPlugin` by [WebpackOptionsApply.js](https://github.com/webpack/webpack/blob/webpack-4/lib/WebpackOptionsApply.js)
=> parse `app.config.ts`by child compilers
=> inject `compiler.options`
After:
use `false` in `webpack.config.js`
=> prevent loading these plugins
=> parse `app.config.ts`by child compilers
=> load these plugins manually in `GojiChunksWebpackPlugin`
The benefit of this changing is that we no long need to depend on internal runtime order of `SplitChunksPlugin` and `RuntimeChunkPlugin`. We can create the instance of plugins after finishing param initializing.
P.S. This PR may also solve the `cacheGroups` compatibility issue in [Webpack 5](https://github.com/airbnb/goji-js/pull/22).
> Refactor SplitChunksPlugin and RuntimeChunkPlugin injecting logic

- packages/core/src/__tests__/helpers/adaptor.ts
- packages/core/src/lifecycles/universal/__tests__/renderedEffect.test.tsx
- packages/core/src/lifecycles/universal/renderedEffect.ts
- packages/core/src/utils/__tests__/effects.test.ts
- packages/core/src/utils/effects.ts
Usage:
```tsx
useRenderedEffect(() => {
// init here
return () => {
// clean-up here
}
}, []);
```
Here is an example with Goji blocking mode enabled. A React component commits ( renders ) 3 times, its 2nd/3rd commit happen while 1st setData is still working.
<details>
<summary>source</summary>
```
title useRenderedEffect
note over React: mount
React->buffer: commit a
buffer->setData: a
setData->(2)webview: render a
React->buffer: commit b
React->buffer: commit c
webview->(2)setData: done a
setData-->useRenderedEffect: effect a
buffer->setData: b+c
setData->(2)webview: render b+c
webview->(2)setData: done b+c
setData-->useRenderedEffect: clean-up a
setData-->useRenderedEffect: effect b
setData-->useRenderedEffect: clean-up b
setData-->useRenderedEffect: effect c
note over React: unmount …
```
> Refactor useRenderedEffect to support clean-up callback

- packages/core/src/reconciler/instance.ts
- packages/core/src/utils/__tests__/eventChannel.test.ts
- packages/core/src/utils/eventChannel.ts
- packages/core/tsconfig.json
`EventChannel` is a pub-sub event hub implementation.
It's mainly inspired from built-in `events` library but also provides several important new features.
1. `EventChannel` is type-safed.
2. No `event name`, use data payload instead.
3. `EventChannel` provides a duplexed channel from both pub-to-sub and sub-to-pub by returning a value from listener callback. See example bellow.
```tsx
const channel = new EventChannel<string, string>;
channel.on(msg => msg.toUpperCase());
channel.on(msg => msg.toLowerCase());
channel.emit('Hello'); // returns ['HELLO', 'hello']
```
1. EventChannel provides more features than EventEmitter.
2. EventChannel cost less lines of code ( ~ 180 lines) than [EventEmitter](https://github.com/browserify/events/blob/main/events.js) ( ~ 500 lines )
3. Prevent …
> Implement EventChannel / CachedEventChannel as replacement of EventEmitter

- packages/core/src/adaptor/wechat.tsx
- packages/core/src/components/__tests__/eventProxy.test.tsx
- packages/core/src/components/eventProxy.tsx
- packages/core/src/components/index.tsx
- packages/core/src/container.tsx
- packages/core/src/lifecycles/native/__tests__/hooks.test.tsx
- packages/core/src/lifecycles/native/hooks.ts
- packages/core/src/lifecycles/types.ts
- packages/core/src/lifecycles/universal/__tests__/hooks.test.tsx
- packages/core/src/lifecycles/universal/__tests__/renderedEffect.test.tsx
- packages/core/src/lifecycles/universal/provider.tsx
- packages/core/src/lifecycles/universal/renderedEffect.ts
`EventProxy` is the most important event bus in GojiJS. It enabled communication between container ( React Reconciler ) and React components.
According to last PR https://github.com/airbnb/goji-js/pull/117 I refactor the `EventProxy` in new `EventChannel` class and deprecate the `events`.
> Refactor EventProxy with EventChannel

- packages/core/src/lifecycles/universal/__tests__/hooks.test.tsx
- packages/core/src/lifecycles/universal/context.ts
- packages/core/src/lifecycles/universal/hooks.ts
- packages/core/src/lifecycles/universal/provider.tsx
- packages/core/src/lifecycles/universal/renderedEffect.ts
- packages/core/src/reconciler/hostConfig.ts
- packages/core/src/reconciler/index.ts
- packages/core/src/subtreeAttachEvents.ts
- packages/core/src/utils/eventChannel.ts
This is the last part of https://github.com/airbnb/goji-js/pull/117 that replace all `events` with new `EventChannel` including
1. Universal hooks / useRenderedEffect
2. `Object.e` events ( component attached / de-attached )
3. `useRef`
> Refactor all events with EventChannel

- packages/core/src/lifecycles/universal/provider.tsx
This typo cause `useVisibility` doesn't call when `onHide` or second `onShow`.
> Fix a typo in useVisibility

- packages/cli/package.json
- packages/cli/src/config/postcss.config.ts
- packages/cli/src/config/postcssPx2units.ts
- yarn.lock
This PR forked the [postcss-px2units](https://github.com/yingye/postcss-px2units) and refactored it to support PostCSS 8.
> Refactor postcss-px2units to support PostCSS 8

- packages/cli/src/config/webpack.config.ts
Since we upgraded to Webpack 5, some global variables won't be shimmed automatically any more. So I use `DefinePlugin` to add them back.
Unfortunately I missed the `Buffer` in previous PR and cause code like `Buffer.from` fails to run.
> Fix missing Buffer

- packages/cli/src/config/postcssConfig.ts
- packages/cli/src/config/webpack.config.ts
[This issue](https://github.com/csstools/postcss-preset-env/issues/232) provides a performance improvement solution, that we can disable autoloading config to speed up `postcss-preset-env`.
> Improve PostCSS performance

- packages/cli/package.json
- packages/cli/src/config/loaders.ts
- packages/cli/src/config/webpack.config.ts
- yarn.lock
This PR removed support of preprocess for these reasons:
1. Developers can use [`process.env.TARGET`](https://goji.js.org/docs/en/cross-platform#conditions-in-javascript-code) in JS / CSS-in-JS / JSX.
2. There is a [bug in preprocess-loader](https://github.com/airbnb/goji-js/blob/80696cfbe8324a6f39d7411f54bf0e7e3059a648/packages/cli/src/config/loaders.ts#L17-L25) and the bugfix cannot work with worker_threads based `thread-loader`.
3. `preprocess` cost extra building time.
> Remove preprocess-loader

- packages/beemo-dev/package.json
- packages/cli/package.json
- packages/cli/src/config/linariaFileCache.ts
- packages/cli/src/config/webpack.config.ts
- packages/cli/src/index.ts
- packages/demo-todomvc-linaria/package.json
- packages/demo-todomvc/package.json
- yarn.lock
Linaria support a new option `cacheProvider` since version 2.3 https://github.com/callstack/linaria/pull/884
We can use this option to make it compatible with `thread-loader`.
> Support Linaria new cacheProvider option

- packages/webpack-plugin/src/plugins/chunks/runtime.ts
- packages/webpack-plugin/src/plugins/chunks/split.ts
- packages/webpack-plugin/src/plugins/nohoist.ts
Before:
`compiler.hooks.compile` => get `appConfig` => `compiler.hooks.thisCompilation`
After:
`compiler.hooks.thisCompilation` => get `appConfig`
In previous implement, I chose `compiler.hooks.compile` to ensure `appConfig` was already inited. But this hook runs each time Webpack re-build, which cause `compiler.hooks.thisCompilation` become larger and larger. 
This is the reason why as re-build happens, the bundling time also increases in Goji CLI watch mode.
> Stop using compiler.hooks.compile to improve build performance

- packages/cli/src/config/webpack.config.ts
`__DEV__` is a [React Native's specific global variable](https://reactnative.dev/docs/javascript-environment#specific) that might be used in some 3rd-party `.native.js` files. 
For example, `@apollo/client`depends on this variable and try to [patch it within `global`](https://github.com/apollographql/apollo-client/blob/212b1e686359a3489b48d7e5d38a256312f81fde/src/utilities/globals/DEV.ts). But unfortunately Mini Program runtime doesn't have a valid `global` variable. So both the `__DEV__` and its patch fail to work.
In this PR I use `webpack.DefinePlugin` to replace all `__DEV__` usage in source code so the bug should be fixed.
> Support React Native's global variable `__DEV__`

- packages/create-goji-app/templates/src/project.config.json
- packages/create-goji-app/templates/src/project.qq.json
- packages/create-goji-app/templates/src/project.swan.json
- packages/demo-todomvc-linaria/src/project.config.json
- packages/demo-todomvc-linaria/src/project.qq.json
- packages/demo-todomvc-linaria/src/project.swan.json
- packages/demo-todomvc/src/project.config.json
- packages/demo-todomvc/src/project.qq.json
- packages/demo-todomvc/src/project.swan.json
- packages/webpack-plugin/src/plugins/__tests__/fixtures/hoist/src/project.config.json
- packages/webpack-plugin/src/plugins/__tests__/fixtures/hoist/src/project.qq.json
- packages/webpack-plugin/src/plugins/__tests__/fixtures/hoist/src/project.swan.json
The lib version field tells dev tool to use specific version of SDK. In most cases we prefer to the latest version.
So this PR removed these fields in GojiJS repo.
WeChat: `libVersion`
QQ: `qqLibVersion`
Baidu: `swan.baiduboxapp.swanJsVersion`
> Remove default `libVersion` fields in `project.config.json`

- packages/webpack-plugin/src/constants/components.ts
Wrapped components aim to resolve unexpected property change issues.
For example the `focus` property of `input` and `textarea` triggers a focus action each time when `this.setData` called. But in React world we expect it only happen when `focus` becomes `true` from `false`.
The wrapped component prevent useless `setData` by `observe` method to fix this issue. Because it's a custom component we need to test it carefully on each enabled platform.
> Enable wrapped input/textarea for baidu

- packages/webpack-plugin/src/constants/components.ts
- packages/webpack-plugin/src/plugins/bridge.ts
- packages/webpack-plugin/src/templates/commons/__tests__/nativeComponentJson.test.ts
- packages/webpack-plugin/src/templates/commons/__tests__/wxmlElement.test.ts
- packages/webpack-plugin/src/templates/commons/nativeComponentJson.ts
- packages/webpack-plugin/src/templates/commons/wxmlElement.ts
- packages/webpack-plugin/src/templates/components/__tests__/components.wxml.test.tsx
- packages/webpack-plugin/src/templates/components/components.wxml/index.tsx
- packages/webpack-plugin/src/templates/components/item.json.ts
- packages/webpack-plugin/src/templates/components/leaf-components.wxml.ts
- packages/webpack-plugin/src/templates/components/subtree.json.ts
- packages/webpack-plugin/src/templates/components/wrapped.js.ts
- packages/webpack-plugin/src/templates/components/wrapped.json.ts
- packages/webpack-plugin/src/templates/components/wrapped.wxml.ts
- packages/webpack-plugin/src/utils/__tests__/components.test.ts
- packages/webpack-plugin/src/utils/components.ts
- packages/webpack-plugin/src/utils/pluginComponent.ts
This PR refactor internal code without feature changing.It split component desc interface into 3 different types:
* `ComponentDesc`: native components like `view` / `map`.
* `SimplifiedComponentDesc`: `ComponentDesc` with a `simplifiedId`.
* `PluginComponentDesc`: components from plugin which usually has a `nativePath`.
> Refactor ComponentDesc

- packages/webpack-plugin/src/templates/commons/wrapped.ts
- packages/webpack-plugin/src/templates/components/__tests__/__snapshots__/children.wxml.test.tsx.snap
- packages/webpack-plugin/src/templates/components/__tests__/__snapshots__/wrapped.js.test.tsx.snap
- packages/webpack-plugin/src/templates/components/__tests__/components.wxml.test.tsx
- packages/webpack-plugin/src/templates/components/__tests__/wrapped.js.test.tsx
- packages/webpack-plugin/src/templates/components/children.wxml.ts
- packages/webpack-plugin/src/templates/components/components.wxml/index.tsx
- packages/webpack-plugin/src/templates/components/subtree.js.ts
- packages/webpack-plugin/src/templates/components/subtree.wxml.ts
- packages/webpack-plugin/src/templates/components/wrapped.js.ts
- packages/webpack-plugin/src/templates/components/wrapped.wxml.ts
There is no need to separate passing every props into a wrapped component and a `meta` variable is enough. Therefor we can refactor current implement to save more bundle size.
> Refactor wrapped component with `meta`

- packages/core/src/components/subtree.ts
- packages/core/src/constants.ts
- packages/core/src/index.ts
- packages/core/src/reconciler/__tests__/getSubtreeId.noSubtree.test.tsx
- packages/core/src/reconciler/__tests__/getSubtreeId.test.tsx
- packages/core/src/reconciler/__tests__/instance.test.tsx
- packages/core/src/reconciler/instance.ts
- packages/webpack-plugin/src/constants/features.ts
- packages/webpack-plugin/src/plugins/bridge.ts
- packages/webpack-plugin/src/templates/commons/wrapped.ts
- packages/webpack-plugin/src/templates/components/__tests__/__snapshots__/children.wxml.test.tsx.snap
- packages/webpack-plugin/src/templates/components/__tests__/children.wxml.test.tsx
- packages/webpack-plugin/src/templates/components/__tests__/wrapped.js.test.tsx
- packages/webpack-plugin/src/templates/components/children.wxml.ts
- packages/webpack-plugin/src/templates/components/components.wxml/index.tsx
- packages/webpack-plugin/src/templates/components/item.wxml.ts
- packages/webpack-plugin/src/templates/components/leaf-components.wxml.ts
- packages/webpack-plugin/src/templates/components/subtree.wxml.ts
- packages/webpack-plugin/src/templates/components/wrapped.js.ts
- packages/webpack-plugin/src/templates/components/wrapped.wxml.ts
1. Refactored `item.wxml` to reuse existing `children0.wxml`.
2. Fixed an bug in `getSubtreeId` that cause this function always return `undefined`. The root cause is https://github.com/airbnb/goji-js/pull/77 replace root container with new `GOJI_VIRTUAL_ROOT` element but I forgot to update the `getSubtreeId` logics.
> Refactor template reuse & fix `getSubtreeId`

- CHANGELOG.md
- packages/beemo-dev/configs/lerna.ts
- packages/beemo-dev/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/create-goji-app/package.json
- packages/demo-todomvc-linaria/package.json
- packages/demo-todomvc/package.json
- packages/goji.js.org/package.json
- packages/macro/package.json
- packages/testing-library/package.json
- packages/webpack-plugin/package.json
- **webpack-plugin:** Enable wrapped input/textarea for baidu
[\#165](https://github.com/airbnb/goji-js/pull/165)
- **webpack-plugin:** Refactored the data structure in template and `setData` JSON data.
[\#180](https://github.com/airbnb/goji-js/pull/180)
- **webpack-plugin:** Refactor ComponentDesc [\#181](https://github.com/airbnb/goji-js/pull/181)
- **webpack-plugin:** Refactor wrapped component with `meta`
[\#182](https://github.com/airbnb/goji-js/pull/182)
- **core:** Support NodeJS 18 [\#184](https://github.com/airbnb/goji-js/pull/184)
- **webpack-plugin:** Refactor template reuse & fix `getSubtreeId`
[\#186](https://github.com/airbnb/goji-js/pull/186)
- **create-goji-app:** Remove default `libVersion` fields in `project.config.json` …
> Release v1.1.0

- packages/core/src/events.ts
- packages/core/src/reconciler/__tests__/instance.test.tsx
- packages/core/src/reconciler/instance.ts
This PR fixed https://github.com/airbnb/goji-js/issues/198
Previously, GojiJS used `e.target.dataset` to detect whether an event had been stopped or not. However, this approach failed to work when crossing custom component such as `Subtree` or wrapped components. To improve stability, I have refactored the implementation of `stopPropagation` using the instance tree ( VDOM tree ).
When `stopPropagation` is called on an element, GojiJS marks itself and its ancestors as stopped, and they will no longer accept events with the same `type` and `timeStamp`. Throughout this process, we assume that events with the same type` and `timeStamp` are dispatched from the same source.
> Refactor `stopPropagation` to fix #198

- packages/webpack-plugin/src/constants/features.ts
Before, circular dependency like `include` -> `import` -> `include` works on Baidu. After Baidu upgrade its new compiler on dev tool >= v4.22, it throws an error at compiling time.
To fix the issue, we can reuse the `useInlineChildrenInComponent` feature which Alipay already enabled. This feature copies the content of `children.wxml` into `component.wxml` and could increase a little bundle size.
Docs: https://smartprogram.baidu.com/docs/develop/devtools/beta-notify#_5-%E6%A8%A1%E6%9D%BF-import-%E8%AF%AD%E6%B3%95%E4%B8%8D%E5%85%81%E8%AE%B8%E5%BE%AA%E7%8E%AF%E5%BC%95%E7%94%A8%E3%80%82
> Inline the content of `children.wxml` into `component.wxml` to support new Baidu compiler on dev tool >= v4.22

- packages/webpack-plugin/src/constants/features.ts
- packages/webpack-plugin/src/plugins/bridge.ts
- packages/webpack-plugin/src/templates/components/__tests__/leaf-components.wxml.test.tsx
- packages/webpack-plugin/src/templates/components/components.wxml/index.tsx
- packages/webpack-plugin/src/templates/components/leaf-components.wxml.ts
As I mentioned in https://github.com/airbnb/goji-js/issues/140 , Alipay now force to enable Lib v2.0 so we need to refactor the `.axml` template to fix the compiling issue.
> Prevent using `<include>` in `<template>` to fix #140 on Alipay 

- packages/testing-library/src/__tests__/events.test.tsx
- packages/testing-library/src/events.ts
In some case, we need to test `onLoad` and `onError` event on Image component, in this PR we extends the FireEvent lib to support those events.
> support fire load and error event in test library

- packages/create-goji-app/templates/src/project.config.json
- packages/create-goji-app/templates/src/project.qq.json
- packages/demo-todomvc-linaria/src/project.config.json
- packages/demo-todomvc-linaria/src/project.qq.json
- packages/demo-todomvc/src/project.config.json
- packages/demo-todomvc/src/project.qq.json
- packages/webpack-plugin/src/plugins/__tests__/fixtures/hoist/src/project.config.json
- packages/webpack-plugin/src/plugins/__tests__/fixtures/hoist/src/project.qq.json
[Code protects](https://developers.weixin.qq.com/miniprogram/dev/devtools/project.html#%E6%9C%AC%E5%9C%B0%E8%AE%BE%E7%BD%AE) fails to work on some 3rd-party library like [lodash](https://github.com/lodash/lodash/blob/2da024c3b4f9947a48517639de7560457cd4ec6c/.internal/nodeTypes.js#L20). This PR disabled that option for `create-goji-app` and demo apps.
> Disable code protect option for wechat and qq

- packages/webpack-plugin/src/index.ts
In https://github.com/airbnb/goji-js/pull/120 it said _`nohoist.enable` is set to false in development mode to speed up code bundling._ 
But recently we meet an unexpected issue, that some global CSS styles in a page polluted other page. Consider we have a sub-package `packageA` and a page `packageA/pages/index` inside it with these CSS:
```css
:global() {
page {
background-color: red;
}
}
```
If `nohoist.enable` was `false`, these lines of code would be bundled into `_goji_commons.wxss` and shared by all pages. Which means all pages' background became red.
Therefore, I decided to enable this option by default in case of different behavior on production and development mode.
Also, I tested and found the bundling performance affect is acceptable. See the result of re-bundling time costs ( …
> Enable `nohoist` by default

- packages/cli/src/config/loaders.ts
- packages/cli/src/config/webpack.config.ts
- packages/cli/src/index.ts
This PR adds a new option `parallel` in `goji.config.js`.
```tsx
interface GojiConfig {
...
parallel?:
| {
minimize?: number;
loader?: number;
}
| number;
}
```
The `parallel.minimize` corresponds the `parallel` option within [`TerserWebpackPlugin`](https://webpack.js.org/plugins/terser-webpack-plugin/), while the `parallel.loader` corresponds the `workers` option within [`thread-loader`](https://webpack.js.org/loaders/thread-loader/).
> Add `parallel` option in goji.config.js

- packages/cli/package.json
- packages/cli/src/config/webpack.config.ts
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/plugins/chunks/split.ts
- packages/webpack-plugin/src/plugins/entry.ts
- packages/webpack-plugin/src/plugins/nohoist.ts
- packages/webpack-plugin/src/plugins/runtime.ts
- packages/webpack-plugin/src/plugins/singleton.ts
- packages/webpack-plugin/src/utils/chunkName.ts
- yarn.lock
> Upgrade latest webpack@5.89.0

- packages/cli/src/config/webpack.config.ts
- packages/cli/src/index.ts
The Webpack cache should be invalidated if:
1. The build target has changed, i.e., when using `yarn start [target]`.
2. The GojiJS version has changed, typically after updating the GojiJS CLI.
3. There has been a change in the `webpack.config.js`. This recommendation is provided in the [Webpack cache configuration documentation](https://webpack.js.org/configuration/cache/#cachebuilddependencies). Additionally, this has been implemented in [Webpack CLI](https://github.com/webpack/webpack-cli/blob/ef09fee7185e5c80efd3de1c98260e61f1e63ba0/packages/webpack-cli/src/webpack-cli.ts#L2279-L2300).
4. There is a change in the `goji.config.js`. This is crucial because users often modify `goji.config.js` to adjust the build configuration.
> Fix Webpack cache invalidation

- packages/cli/src/config/postcssConfig.ts
- packages/cli/src/config/postcssTransformUnit.ts
- packages/cli/src/config/webpack.config.ts
- packages/cli/src/index.ts
- packages/demo-todomvc-linaria/goji.config.js
- packages/demo-todomvc/goji.config.js
- packages/goji.js.org/docs/advanced/config.md
- packages/goji.js.org/i18n/zh/code.json
- packages/goji.js.org/i18n/zh/docusaurus-plugin-content-docs/current/advanced/config.md
- packages/goji.js.org/i18n/zh/docusaurus-plugin-content-docs/current/guide/lifecycle.md
- packages/webpack-plugin/src/plugins/__tests__/hoist.test.ts
This PR introduced a new option `css.unit` in `goji.config.js` to enable CSS unit transforming.
- Type: `undefined | 'keep' | 'to-px' | 'to-rpx'`
- Default: `'to-rpx'`
There is a built-in PostCSS plugin called `postcss-transform-unit` that can be used to transform CSS
units in all files. In some cases, you may want to convert the usage of `px` to `rpx` or vice versa.
You can use this option.
- `keep`: Do not transform any CSS unit.
- `to-px`: Transform `rpx` to `px`. `2rpx` equals to `1px`.
- `to-rpx`: Transform `px` to `rpx`. `1px` equals to `2rpx`.
> The default will be changed to `keep` in the future.
> Refactor CSS unit transforming

- packages/webpack-plugin/src/templates/commons/wrapped.ts
- packages/webpack-plugin/src/templates/components/__tests__/__snapshots__/wrapped.js.test.tsx.snap
We have to memorize the `cursor` attr of `<input>` to fix the issue.
Before:
After:
> Fix <input> cursor issue
