.github/workflows/ci.yml
Create a config file `.github/workflows/ci.yml` to enable CI checking for this repo.
=> Initial github action for CI

packages/webpack-plugin/src/plugins/runtime.ts, packages/webpack-plugin/src/plugins/splitChunks.ts
TL;DR,
Move `require('commons.js')` from `page.js`  to `app.js`. Move `@import 'commons.js'` from `page.wxss` to `app.wxss`.
The reason why make this change is that Alipay always bundles `commons.js` / `commons.wxss` into each sub-packages and cause the whole packages size exceeded 8M limit more easily.
But in GojiJS, we can use `app.js` / `app.wxss` to inject the common chunk, rather than in page entry. Becuase `app` always run before pages init.
=> Change runtime hoist logic for reducing Alipay bundle size

packages/goji.js.org/docs/ref.md, packages/goji.js.org/website/i18n/en.json, packages/goji.js.org/website/i18n/zh-CN.json, packages/goji.js.org/website/sidebars.json, packages/goji.js.org/website/translated_docs/zh-CN/ref.md
This PR adds document for refs and `useReferedEffect`.
=> Add document for refs and useReferedEffect

README.md
=> Add documentation link in README.md

packages/create-goji-app/templates/src/project.qq.json, packages/create-goji-app/templates/src/project.swan.json, packages/create-goji-app/templates/src/project.toutiao.json, packages/demo-todomvc-linaria/src/project.qq.json, packages/demo-todomvc-linaria/src/project.swan.json, packages/demo-todomvc-linaria/src/project.toutiao.json, packages/demo-todomvc/src/project.qq.json, packages/demo-todomvc/src/project.swan.json, packages/demo-todomvc/src/project.toutiao.json
All `project.config.json` files are copied from new empty projects from dev tools.
=> Add project.config.json templates

packages/core/src/components/componentsTypes.ts
The pr is to add the necessary prop
=> add bindMessage prop to goji Webview component

packages/webpack-plugin/src/constants/components.ts, packages/webpack-plugin/src/utils/__tests__/components.test.ts, packages/webpack-plugin/src/utils/components.ts
This PR is the part 2 of https://github.com/airbnb/goji-js/pull/58
Before:
```tsx
export type ComponentDesc = {
props: {
[key: string]: PropDesc;	
};
}
```
After:
```tsx
export type ComponentDesc = {
props: Array<string | [string, PropDesc]>;
}
```
=> Refactor components meta data in webpack plugins part 2

packages/cli/src/config/webpack.config.ts, packages/demo-todomvc/package.json, packages/demo-todomvc/src/app.config.ts, packages/demo-todomvc/src/swan-sitemap/index.tsx, packages/macro/.eslintignore, packages/macro/README.md, packages/macro/babel-jest.config.js, packages/macro/package.json, packages/macro/src/index.ts, packages/macro/src/registerPluginComponent.ts, packages/macro/src/utils/__tests__/transformObjectASTToObject.test.ts, packages/macro/src/utils/transformObjectASTToObject.ts, packages/macro/tsconfig.json, packages/webpack-plugin/package.json, packages/webpack-plugin/src/constants/components.ts, packages/webpack-plugin/src/index.ts, packages/webpack-plugin/src/utils/components.ts, packages/webpack-plugin/src/utils/pluginComponent.ts, packages/webpack-plugin/src/utils/render/index.ts, packages/webpack-plugin/templates/item.json.ejs, yarn.lock
0. Add new dependency `@goji/macro`.
1. Add `plugins` or `dynamicLib` in `app.config.js`.
```ts
dynamicLib: {
'swan-sitemap-lib': {
provider: 'swan-sitemap',
},
}
```
2. Use `registerPluginComponent` for plugin components.
```tsx
import { registerPluginComponent } from '@goji/macro';
const SwanSitemapList = registerPluginComponent(
'baidu',
'swan-sitemap-list',
'dynamicLib://swan-sitemap-lib/swan-sitemap-list',
['list-data', 'current-page', 'total-page', 'path'],
);
const listData = [...];
render(
<SwanSitemapList
listData={listData}
currentPage={1}
totalPage={500}
path="/swan-sitemap/index"
/>,
);
```
Screenshot of `packages/demo-todomvc/src/swan-sitemap/index.tsx`:
For more details see https://github.com/airbnb/goji-js/issues/55
=> Add registerPluginComponent and new package @goji/macro

packages/goji.js.org/docs/hooks.md, packages/goji.js.org/website/blog/2020-09-23-gojijs-from-airbnb.md, packages/goji.js.org/website/translated_docs/zh-CN/hooks.md
=> Fix typo in demo

packages/goji.js.org/docs/css-in-js.md, packages/goji.js.org/docs/plugins.md, packages/goji.js.org/website/i18n/en.json, packages/goji.js.org/website/i18n/zh-CN.json, packages/goji.js.org/website/sidebars.json, packages/goji.js.org/website/translated_docs/zh-CN/css-in-js.md, packages/goji.js.org/website/translated_docs/zh-CN/plugins.md
This PR add documentation of using plugins in GojiJS.
Fixed https://github.com/airbnb/goji-js/issues/55
=> Add documentation of using plugins in GojiJS

packages/webpack-plugin/src/constants/__tests__/components.test.ts, packages/webpack-plugin/src/constants/components.ts
Duplicated events cause template parse error in Toutiao Mini Program.
=> Remove deplicated events in template

packages/webpack-plugin/src/constants/__tests__/components.test.ts, packages/webpack-plugin/src/constants/components.ts, packages/webpack-plugin/src/templates/commons/__tests__/nativeComponentJson.test.ts, packages/webpack-plugin/src/templates/components/wrapped.wxml.ts, packages/webpack-plugin/src/utils/__tests__/components.test.ts, packages/webpack-plugin/src/utils/components.ts, packages/webpack-plugin/src/utils/pluginComponent.ts
Before:
```tsx
{
name: 'view',
props: [
'src',
['url', { required: true, defaultValue: 'aa' }]
]
}
```
After:
```tsx
{
name: 'view',
props: {
src: {
required: false,
type: 'String', // new field
},
url: {
required: true,
type: 'String', // new field
defaultValue: 'aa'
}
}
}
```
After this PR merged, I can implement wrapped component in template string.
```
Component({
properties: {
src: {
type: 'String'
}
}
})
```
=> Refactor component props desc

packages/webpack-plugin/src/templates/components/wrapped.js.ts
=> Refactor `wrapped.js` without breaking change

packages/beemo-dev/configs/jest.ts
This PR fixed `transformIgnorePatterns` in `jest.config.js` to speed up jest.
=> Speed up jest

packages/beemo-dev/configs/eslint.ts, packages/goji.js.org/docs/testing.md, packages/goji.js.org/website/translated_docs/zh-CN/testing.md, packages/testing-library/src/__tests__/queries/text.test.tsx, packages/testing-library/src/queries/text.ts, packages/testing-library/src/rendered.ts
New `ByText` usage:
```tsx
type TextMatch = string | RegExp | ((text: string, node: ReactTestInstance) => boolean);
export interface ByTextOptions {
exact?: boolean;
trim?: boolean;
collapseWhitespace?: boolean;
}
queryAllByText: (
container: ReactTestInstance,
text: TextMatch,
{ exact = true, trim = true, collapseWhitespace = true }: ByTextOptions = {},
) => ReactTestInstance[]
```
=> Enhance ByText query to support RegExp and function

packages/cli/package.json, packages/cli/src/config/fixBabelLoaderForMacro.ts, packages/webpack-plugin/src/loaders/configFile.ts, packages/webpack-plugin/src/loaders/transform.ts
Use `webpack.LoaderDefinition` rather then `webpack.LoaderContext`
=> Fix Webpack loaders typing

packages/create-goji-app/templates/.gitignore
Per #135 , this PR adds a gitignore file to the create goji app template
The template is based off of CRA gitignore file.
https://github.com/facebook/create-react-app/blob/main/.gitignore
=> add gitignore

packages/cli/src/index.ts
From https://webpack.js.org/api/cli/#exit-codes-and-their-meanings
Exit Code | Description
-- | --
0 | Success
1 | Errors from webpack
2 | Configuration/options problem or an internal error
=> Use correct exit code for cli

packages/core/src/components/componentsTypes.ts, packages/webpack-plugin/src/constants/components.ts, packages/webpack-plugin/src/templates/components/__tests__/__snapshots__/wrapped.js.test.tsx.snap
Update native component `textarea`'s props from this doc.
https://developers.weixin.qq.com/miniprogram/dev/component/textarea.html
=> Update `textarea` props

packages/create-goji-app/templates/package.json, packages/create-goji-app/templates/tsconfig.json
Fixed https://github.com/airbnb/goji-js/issues/125
=> Add tsconfig.json for create-goji-app cli

CHANGELOG.md, packages/beemo-dev/configs/lerna.ts, packages/beemo-dev/package.json, packages/cli/package.json, packages/core/package.json, packages/create-goji-app/package.json, packages/demo-todomvc-linaria/package.json, packages/demo-todomvc/package.json, packages/goji.js.org/website/blog/2022-02-22-gojijs-v1.md, packages/goji.js.org/website/package.json, packages/macro/package.json, packages/testing-library/package.json, packages/webpack-plugin/package.json
https://goji.js.org/blog/2022/02/22/gojijs-v1
=> Release v1.0.0

packages/webpack-plugin/src/utils/__tests__/render.test.ts, packages/webpack-plugin/src/utils/render/index.ts
This PR use transform output CSS by regexp to fix https://github.com/airbnb/goji-js/issues/159
=> Fix toutiao calc issue #159

packages/cli/src/config/webpack.config.ts, packages/core/src/render.ts, packages/create-goji-app/templates/package.json, packages/webpack-plugin/src/plugins/projectConfig.ts, yarn.lock
This PR fixed https://github.com/airbnb/goji-js/issues/174 and upgraded all dependencies by `yarn upgrade-interactive`.
=> Upgrade deps & fix missing linaria issue in create CLI template

packages/webpack-plugin/src/templates/components/components.wxml/index.tsx
Fixed https://github.com/airbnb/goji-js/issues/140
=> Add comment for fixing #140

.github/workflows/ci.yml, packages/cli/src/config/linariaFileCache.ts, packages/webpack-plugin/src/plugins/__tests__/hoist.test.ts, packages/webpack-plugin/src/plugins/chunks/split.ts
Replace `md4` with `sha256` to support NodeJS 18
=> Support NodeJS 18

packages/core/src/events.ts
This PR fixed https://github.com/airbnb/goji-js/issues/208
=> Use `event.timestamp` as an alist for `event.timeStamp`

packages/webpack-plugin/src/utils/__tests__/render.test.ts, packages/webpack-plugin/src/utils/render/index.ts
Since https://github.com/airbnb/goji-js/issues/160 has been fixed by Toutiao. We can remove this bugfix now.
=> Remove bugfix for #160

.github/workflows/ci.yml, .github/workflows/docs-deploy.yml, packages/goji.js.org/docs/advanced/config.md, packages/goji.js.org/docs/advanced/css-in-js.md, packages/goji.js.org/docs/advanced/css.md, packages/goji.js.org/docs/advanced/plugins.md, packages/goji.js.org/docs/advanced/sub-packages.md, packages/goji.js.org/docs/advanced/testing.md, packages/goji.js.org/docusaurus.config.js, packages/goji.js.org/i18n/zh/docusaurus-plugin-content-docs/current/advanced/config.md, packages/goji.js.org/i18n/zh/docusaurus-plugin-content-docs/current/advanced/css-in-js.md, packages/goji.js.org/i18n/zh/docusaurus-plugin-content-docs/current/advanced/css.md, packages/goji.js.org/i18n/zh/docusaurus-plugin-content-docs/current/advanced/plugins.md, packages/goji.js.org/i18n/zh/docusaurus-plugin-content-docs/current/advanced/sub-packages.md, packages/goji.js.org/i18n/zh/docusaurus-plugin-content-docs/current/advanced/testing.md, packages/goji.js.org/package.json, yarn.lock
This PR
1. Added documentation for `goji.config.js`
2. Upgraded the [docusaurus](https://docusaurus.io/) to v3.
=> Add documentation for `goji.config.js`

packages/core/src/components/componentsTypes.ts, packages/core/src/components/factoryComponents.ts
support `picker-view-column` component.
=> support picker-view-column component

.github/workflows/ci.yml
Add NodeJS 22 and remove NodeJS 18 in CI.
=> Support NodeJS 22
